labs: osbashauto exit on script error
Make osbashout abort if a client-side scripts returns an error; use a
file named error in the status directory to signal the problem and to
store the name of the offending script for use by Windows batch scripts.

Have osbash.sh and the Windows batch scripts exit when an error file
appears.

Change-Id: I6722e75c9c23b99e5ed25b00429026c2e0ff6a12

diff --git a/labs/scripts/osbash/template-osbashauto b/labs/scripts/osbash/template-osbashauto
--- a/labs/scripts/osbash/template-osbashauto
+++ b/labs/scripts/osbash/template-osbashauto
@@ -36,8 +36,12 @@ for AUTODIR in "/$SHARE_NAME/autostart" "/$SHARE_NAME/autostart/$HOSTNAME"; do
     if [ -d "$AUTODIR" ]; then
         echo "$(date) autodir $AUTODIR"
         for SCRIPT in $AUTODIR/*.sh; do
-            as_root_exec_script "$SCRIPT"
-
+            if ! as_root_exec_script "$SCRIPT"; then
+                echo >&2 "Script returned with error, giving up."
+                # Tell host about the error
+                echo "ERROR in $SCRIPT" >> "$STATUS_DIR/error"
+                exit 1
+            fi
             # Remove script after execution
             rm "$SCRIPT"
         done
